config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('journal/', include('journal.urls', namespace='journal')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/urls.py
from django.urls import path
from journal.apps import JournalConfig
from journal.views import JournalCreateView, JournalListView, JournalDetailView, JournalUpdateView, JournalDeleteView, \
    is_publish

app_name = JournalConfig.name


urlpatterns = [
    path('create/', JournalCreateView.as_view(), name='create'),
    path('', JournalListView.as_view(), name='list'),
    path('view/<int:pk>/', JournalDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', JournalUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', JournalDeleteView.as_view(), name='delete'),
    path('publish/<int:pk>/', is_publish, name='published_is'),
    # path('count_view/<int:pk>/', send_email, name='count_view'),
    # path('count_view/<int:pk>/', send_email, name='count_view'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, reset_password, \
    send_mail_reset_password

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('profile/reset_password/', reset_password, name='reset_password'),
    # path('profile/reset_password/send_mail_reset_password', send_mail_reset_password, name='send_mail_reset_password'),
]

journal/models.py
from django.db import models
from django.template.defaultfilters import slugify

from config.settings import NULLABLE


class Journal(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    picture = models.ImageField(upload_to='pictures_journal/', verbose_name='Изображение(превью)', **NULLABLE)
    data_create = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    published_is = models.BooleanField(default=False, verbose_name='признак публикации')
    count_view = models.PositiveIntegerField(default=0, verbose_name='количество просмотров')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title} ({self.data_create} {self.count_view})'

    class Meta:
        verbose_name = 'журнал'
        verbose_name_plural = 'журналы'

journal/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template.base import logger
from django.urls import reverse_lazy, reverse

from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from journal.models import Journal

from django.core.mail import send_mail


class JournalCreateView(CreateView):
    model = Journal
    fields = ('title', 'content',)
    success_url = reverse_lazy('journal:list')

    # def form_valid(self, form):
    #     if form.is_valid:
    #         new_journal = form.save()
    #         new_journal.slug = slugify(new_journal.title)
    #         new_journal.save()
    #
    #     return super().form_valid(form)


class JournalUpdateView(UpdateView):
    model = Journal
    fields = ('title', 'content',)

    # success_url = reverse_lazy('journal:list')

    def form_valid(self, form):
        if form.is_valid:
            new_journal = form.save()
            new_journal.slug = slugify(new_journal.title)
            new_journal.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('journal:view', args=[self.kwargs.get('pk')])


class JournalListView(ListView):
    model = Journal

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(published_is=False)
        return queryset


class JournalDetailView(DetailView):
    model = Journal

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_view += 1
        self.object.save()
        if self.object.count_view == 100:
            send_mail_about_100_views(self.object.id)
        return self.object


class JournalDeleteView(DeleteView):
    model = Journal
    success_url = reverse_lazy('journal:list')


def is_publish(request, pk):
    journal_item = get_object_or_404(Journal, pk=pk)
    if journal_item.published_is:
        journal_item.published_is = False
    else:
        journal_item.published_is = True
    journal_item.save()

    return redirect(reverse('journal:list'))


def send_mail_about_100_views(journal_id: int):
    journal = Journal.objects.get(pk=journal_id)
    if journal.count_view != 100:
        logger.error(
            'Функция вызвана для статьи %d, к которой %d просмотров',
            journal.pk, journal.count_view
        )
    return send_mail(subject='Популярная статья',
                     message=f'Статья {journal.title} была просмотрена 100 раз',
                     from_email="shievanov.egor@yandex.ru",
                     recipient_list=["egor.shievanov@gmail.com"],
                     fail_silently=False,
                     )

journal/templates/journal/journal_confirm_delete.html
{% extends 'catalog/base_pricing.html' %}

{% block content_journal %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card" type="center">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить эту запись "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                            <a href="{% url 'journal:list' %}" class="btn btn-success">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

journal/templates/journal/journal_detail.html
{% extends 'catalog/base_pricing.html' %}


{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card_header">
                    <h3 class="card-title">
                        Журнал {{ object.title }} ({{ object.slug }})
                    </h3>
                    <img src="..." class="card-img-top" alt="Card image cap">
                </div>
                <div class="card-body">
                    <p>
                        {{ object.content }}
                    </p>
                    <table class="table">
                        <tr>
                            <td>Дать создания</td>
                            <td>{{ object.data_create }}</td>
                        </tr>
                        <tr>
                            <td>Количество просмотров</td>
                            <td>{{ object.count_view }}</td>

                        </tr>
                    </table>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

journal/templates/journal/journal_form.html
{% extends 'catalog/base_pricing.html' %}

{% block content_journal %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card" type="center">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-danger">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

journal/templates/journal/journal_list.html
{% extends 'catalog/base_pricing.html' %}
{% load my_tags %}
{% block content %}
<div class="coc-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'journal:create' %}">Добавить товар</a>
</div>

{% for object in object_list %}
<div class="col md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{ object|title }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'journal:view' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">View</a>
                    <a href="{% url 'journal:edit' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="{% url 'journal:delete' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Delete</a>
                </div>
                    {% if object.published_is %}
                        <a class="btn btn-success" href="{% url 'journal:published_is' object.pk %}" type="button">Publish</a>
                    {% else %}
                        <a class="btn btn-warning" href="{% url 'journal:published_is' object.pk %}" type="button">not Publish</a>
                    {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div class="card" style="width: 18rem;">
    <img src="" class="card-img-top" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">Заголовок карточки</h5>
        <p class="card-text">Небольшой пример текста, который должен основываться на названии карты и составлять
            основную часть содержимого карты.</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Элемент</li>
        <li class="list-group-item">Второй элемент</li>
        <li class="list-group-item">Третий элемент</li>
    </ul>
    <div class="card-body">
        <a href="#" class="card-link">Ссылка карточки</a>
        <a href="#" class="card-link">Другая ссылка</a>
    </div>
</div>
{% endblock %}