catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, ProductTemplateView, VersionDetailView, VersionUpdateView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view'),
    path('contact/', cache_page(60)(ProductTemplateView.as_view()), name='contact'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    # path('create_version/', VersionCreateView.as_view(), name='create_version'),
    path('edit_version/<int:pk>/', VersionUpdateView.as_view(), name='edit_version'),
    path('view_version/<int:pk>/', cache_page(60)(VersionDetailView.as_view()), name='view_version'),
    path('list_category/', CategoryListView.as_view(), name='list_category'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('journal/', include('journal.urls', namespace='journal')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, reset_password, \
    send_mail_reset_password

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('profile/reset_password/', reset_password, name='reset_password'),
    # path('profile/reset_password/send_mail_reset_password', send_mail_reset_password, name='send_mail_reset_password'),
]

catalog/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q

from config.settings import NULLABLE


class Product(models.Model):
    name = models.CharField(max_length=250, verbose_name='Наименование', db_comment='поле для названия продукта',
                            unique=True)
    description = models.TextField(verbose_name='Описание')
    pictures = models.ImageField(upload_to='pictures_prod/', verbose_name='Изображение(превью)', **NULLABLE)
    category = models.IntegerField(verbose_name='категория')
    price = models.IntegerField(verbose_name='цена за покупку')
    data_of_creation = models.DateTimeField(default='2018-11-20T15:58:44.767594-06:00', verbose_name='дата создания')
    data_end_change = models.DateTimeField(auto_now_add=True, verbose_name='дата последнего изменения')

    product_creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                                        verbose_name='создатель продукта')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.name}/{self.description}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        constraints = [
            models.CheckConstraint(
                check=Q(price__gte=100) | Q(price__isnull=True),
                name="price_gte_100",
                violation_error_message='Цена должна быть выше 100 рублей'
            ),
        ]
        permissions = [
            (
                "set_published_status",
                "Can publish product"
            )
        ]


class Category(models.Model):
    name = models.CharField(max_length=250, verbose_name='Наименование', unique=True)
    description = models.TextField(verbose_name='Описание')

    # created_at = models.DateTimeField(**NULLABLE)
    def __str__(self):
        return f'{self.name}: {self.description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Version(models.Model):
    product_name = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.PositiveIntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=250, verbose_name='название версии')
    version_is_active = models.BooleanField(verbose_name='Активность')

    def __str__(self):
        return f'{self.product_name}/{self.version_name} - {self.version_number}: {self.version_is_active}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'
        constraints = [
            models.UniqueConstraint(
                fields=['product_name'],
                condition=Q(version_is_active=True),
                name='only_one_active_version_for_product',
                violation_error_message='Выберите одну активную версию'
            ),
        ]

catalog/forms.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q

from catalog.models import Product, Version
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Button, Fieldset
from crispy_forms.bootstrap import FormActions, ContainerHolder

from config.settings import EXCLUDE_WORD


class ProductForm(forms.ModelForm):
    def clean_name(self):
        data = self.cleaned_data['name']
        for word in EXCLUDE_WORD:
            # if word in data['name']:
            if word in data:
                raise ValidationError('Запрещенные слова не допускаются')
        return data

    def clean_description(self):
        data = self.cleaned_data['description']
        for word in EXCLUDE_WORD:
            # if word in data['description']:
            if word in data:
                raise ValidationError('Запрещенные слова не допускаются')
        return data

    class Meta:
        model = Product
        # fields = '__all__'
        fields = ('name', 'description', 'category', 'price', 'is_published', )


class VersionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-7'
        # self.helper.layout = Layout(
        #     Fieldset(
        #         'Версия продукта',
        #         'product_name',
        #         'version_number',
        #         'version_name',
        #         'version_is'
        #     ),
        #     FormActions(
        #         Submit('save', 'Save changes', css_class='btn-success mt-4'),
        #         Button('cancel', 'Cancel', css_class='btn-warning mt-4 pl-4', ),
        #     ),
        #
        # )

        self.helper.layout = Layout(
            ContainerHolder(
                'product_name',
                'version_number',
                'version_name',
                'version_is_active',
                css_id='text-center',
                css_class='p-3 bg-secondary bg-gradient text-white'
            ),
            FormActions(
                Submit('save', 'Save changes', css_class='btn-success mt-4', css_id=''),
                Button('cancel', 'Cancel', css_class='btn-warning mt-4 pl-4', onclick="window.history.back()"),
            )
        )

    class Meta:
        model = Version
        fields = '__all__'
        # fields = ('product_name', 'version_number', 'version_name', 'version_is_active',)
        # exclude = ('',)


class VersionFormProduct(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.db import IntegrityError
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from .forms import ProductForm, VersionForm, VersionFormProduct
from .models import Product, Version, Category
from django.contrib import messages
from django.http import JsonResponse, HttpResponse, Http404

from .services import cache_category


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLED:
            context_data['category_list'] = cache_category()
        return context_data

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     queryset = Category.objects.all()
    #     if settings.CACHE_ENABLED:
    #         key = 'categories'
    #         cache_data = cache.get(key)
    #         if cache_data is None:
    #             cache_data = queryset
    #             cache.set(key, cache_data)
    #             print(cache_data)
    #         return cache_data
    #
    #     return queryset


class ProductListView(LoginRequiredMixin, ListView):
    model = Product


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class VersionDetailView(LoginRequiredMixin, DetailView):
    model = Version


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    # fields = ('name', 'description', 'category', 'price', 'pictures',)
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        self.object = form.save()
        self.object.product_creator = self.request.user
        self.object.save()

        return super().form_valid(form)


# class VersionCreateView(CreateView):
#     model = Version
#     form_class = VersionForm
#     success_url = reverse_lazy('catalog:home')


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    # fields = ('name', 'description', 'category', 'price', 'pictures',)
    success_url = reverse_lazy('catalog:home')
    error_message = "Оставьте одну активную версию"
    permission_required = 'catalog.change_product'

    # def form_invalid(self, form):
    #     messages.error(self.request, self.error_message)
    #     return super().form_invalid(form)

    # def form_invalid(self, form):
    #     response = super().form_invalid(form)
    #     if self.request.accepts('catalog:home'):
    #         return response
    #     else:
    #         return JsonResponse(form.errors, status=400)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionFormProduct, extra=1)
        obj = self.object
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=obj)
        else:
            context_data['formset'] = VersionFormset(instance=obj)

        return context_data

    # def get_object(self, queryset=None):
    #     self.object = super().get_object(queryset)
    #     if self.request.user.is_superuser:
    #         return self.object
    #     elif self.object.product_creator != self.request.user:
    #         raise Http404
    #     else:
    #         return self.object

    # def has_permission(self):
    #     """
    #     Если у пользователя нет прав на редактирование выдаёт ошибку 403
    #     """
    #     perms = self.get_permission_required()
    #     product: Product = self.get_object()
    #     return self.request.user == product.product_creator

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_form(self):
        """
        Метод для скрытия полей редактирования продукта в edit, если пользователь не его создатель
        """
        form = super().get_form()
        if self.request.user != form.instance.product_creator:  # сравниваем авторизированного пользователя с создателем продукта
            enabled_fields = set()  # метод для добавления полей для чего ???
            if self.request.user.has_perm(
                    'catalog.change_name'):  # если у пользователя есть права на редактирования то разрешаем редактирование этого пользователя
                enabled_fields.add('name')  # добавляем поле для редактирования
            if self.request.user.has_perm('catalog.change_description'):
                enabled_fields.add('description')
            if self.request.user.groups.filter(name='Модератор').exists(): # Если пользователь принадлежит к группе "Модератор", то ему можно изменять поля
                enabled_fields.add('is_published')  # добавляем поле для редактирования

            if self.request.user.is_superuser:
                enabled_fields.add('price')  # добавляем поле для редактирования
                enabled_fields.add('category')  # добавляем поле для редактирования
                enabled_fields.add('is_published')  # добавляем поле для редактирования

            for field_name in enabled_fields.symmetric_difference(form.fields):
                form.fields[field_name].disabled = True
                form.errors.pop(field_name, None)

        return form


class VersionUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:home')
    permission_required = 'catalog.change_version'


# def index(request):
#     context = {'form': VersionForm()}
#     return render(request, 'version_form.html', context)


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')
    permission_required = 'catalog.delete_product'


class ProductTemplateView(TemplateView):
    model = Product
    template_name = 'catalog/contact.html'

    def post(self, request, *args, **kwargs):
        # в переменной request хранится информация о методе, который отправлял пользователь
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        # а также передается информация, которую заполнил пользователь
        print(name, email, message)

        return render(request, 'catalog/contact.html')

catalog/templates/catalog/base_cover.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">
<head>
    <script src='{% static "js/color-modes.js" %}'></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>Cover Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/cover/">


    <link rel="stylesheet" href="{% static 'css/css@3.css' %}">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-bg-dark">
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="container py-3">
        {% include 'catalog/includes/inc_catalog_menu.html' %}
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

    {% block content %}
    {% endblock %}
    {% block content_image %}
    {% endblock %}
</div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</div>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base_pricing.html' %}
{% load my_tags %}

{% block content_table %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">id</th>
        <th scope="col">Названия</th>
        <th scope="col">Описание</th>
    </tr>
    </thead>
    {% if category_list %}
    <ul>
        {% for object in category_list %}
        <tbody>
        <tr>
            <th>{{ object.pk }}</th>
            <th>{{ object.name }}</th>
            <th>{{ object.description }}</th>
        </tr>
        </tbody>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</table>

{% endblock %}

catalog/templates/catalog/contact.html
{% extends 'catalog/base_cover.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="container-fluid">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Contact</h5>
                        <h6 class="card-subtitle mb-2 text-body-secondary">for feedback</h6>
                        <p class="card-text">email: alice@bk.ru</p>
                        <p class="card-text">adress: Wonderland, rabbit hole</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="name" class="form-label">Your name</label>
                    <input type="text" name="name" id="name"/><br>
                </div>
                <div class="mb-3">
                    <label for="Email" class="form-label">Email address</label>
                    <input type="email" name="email" id="Email"/><br>
                </div>
                <div class="mb-3">
                    <label for="message" class="form-label">message</label>
                    <textarea class="form-control" name="message" id="message" rows="3"></textarea>
                </div>
                <input type="submit" value="submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block content_image %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">


    <main class="px-3">
        <h1>Cover your page.</h1>
        <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the
            text, and add your own fullscreen background photo to make it your own.</p>
        <p class="lead">
            <a href="#" class="btn btn-lg btn-light fw-bold border-white bg-white">Learn more</a>
        </p>
    </main>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base_pricing.html' %}

{% block content_journal %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card" type="center">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить эту запись "{{ object.name }}"?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                            <a href="{% url 'catalog:home' %}" class="btn btn-success">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base_pricing.html' %}
{% load my_tags %}
{% block content_title %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal text-body-emphasis">Wonderland</h1>
    <p class="fs-5 text-body-secondary">Choose your team</p>
</div>
{% endblock %}

{% block content_table %}
{% if perms.catalog.add_product %}
<a
        class="btn btn-outline-primary" href="{% url 'catalog:create' %}">Добавить продукт
</a>
{% endif %}
<table class="table">

    <thead>
    <tr>
        <th scope="col">id</th>
        <th scope="col">Названия</th>
        <th scope="col">Цена</th>
        <th scope="col">Описание</th>
        <th scope="col">Работа с продуктом</th>
        <th scope="col">Работа с версиями</th>
        <th scope="col">Активная версия</th>
        <th scope="col">Создатель продукта</th>
        <th scope="col">Публикация продукта</th>
    </tr>
    </thead>
    {% if product_list %}
    <ul>
        {% for product in product_list %}
        <tbody>
        <tr>
            <th>{{ product.id }}</th>
            <th>{{ product.name }}</th>
            <th>{{ product.price }}</th>
            <th>{{ product.description | truncatechars:100}}</th>
            <th>
                <a href="{% url 'catalog:view' product.pk %}"
                   class="btn btn-sm btn-outline-secondary">Просмотр</a>
                {% if perms.catalog.change_product %}

                <a href="{% url 'catalog:edit' product.pk %}"
                   class="btn btn-sm btn-outline-secondary">Изменение</a>

                {% endif %}
                {% if perms.catalog.delete_product %}
                <a href="{% url 'catalog:delete' product.pk %}"
                   class="btn btn-sm btn-outline-secondary">Удаление</a>
                {% endif %}
            </th>
            <th>
                <a href="{% url 'catalog:view_version' product.pk %}"
                   class="btn btn-sm btn-outline-secondary">Просмотр версии</a>
                {% if perms.catalog.change_version %}
                <a href="{% url 'catalog:edit_version' product.pk %}"
                   class="btn btn-sm btn-outline-secondary">Изменение версии</a>
                {% endif %}
            </th>
            <th>
                {% for version in product.version_set.all %}
                {% if version.version_is_active %}
                <p class="text-success">{{ version.version_name }}</p>
                {% else %}
                <p class="text-danger">{{ version.version_name }}</p>

                {% endif %}
                {% endfor %}
            </th>
            <th>
                {% if product.product_creator %}
                {{ product.product_creator }}
                {% endif %}
            </th>
            <th>
                {% if product.is_published != False %}
                <p class="text-success">Опубликовано</p>
                {% else %}
                <p class="text-danger">Не Опубликовано</p>
                {% endif %}
            </th>
        </tr>
        </tbody>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</table>

{% endblock %}

{% block content_buy %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Free</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">$0<small
                        class="text-body-secondary fw-light">/mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>White Rabbit</li>
                    <li>Mad Hatter</li>
                </ul>
                <button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm ">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Pro</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">$15<small
                        class="text-body-secondary fw-light">/mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Cheshire Cat</li>
                    <li>Caterpillar</li>
                </ul>
                <button type="button" class="w-100 btn btn-lg btn-primary">Get started</button>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
            <div class="card-header py-3 text-bg-primary border-primary">
                <h4 class="my-0 fw-normal">Enterprise</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">$29<small
                        class="text-body-secondary fw-light">/mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Tweedledum</li>
                    <li>Tweedledee</li>
                </ul>
                <button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}